# -*- coding: utf-8 -*-
"""
ARIA Overleaf Integration Service  v1.0
========================================
Integrates pyoverleaf to push generated research papers directly to Overleaf.

Architecture:
  - Authenticates via browser cookies (Chrome/Firefox) — no password required.
  - Creates a new Overleaf project via Overleaf's internal REST API.
  - Uploads the LaTeX .tex file + bibliography .bib via pyoverleaf.
  - Returns the project URL for the Obsidian plugin to display as a clickable link.
  - Lists and deletes ARIA-generated Overleaf projects.

Requirements:
  pip install pyoverleaf websocket-client browser-cookie3 beautifulsoup4

Author: ARIA Backend — Overleaf Integration
"""

import logging
import io
import json
import re
import time
from datetime import datetime
from typing import Optional, List, Dict, Any

logger = logging.getLogger(__name__)

# ── Lazy import guard for optional pyoverleaf dep ─────────────────────────────
try:
    import pyoverleaf
    from pyoverleaf import Api as OverleafApi
    _PYOVERLEAF_AVAILABLE = True
except ImportError:
    _PYOVERLEAF_AVAILABLE = False
    logger.warning(
        "[Overleaf] pyoverleaf not installed. "
        "Run: pip install pyoverleaf websocket-client browser-cookie3"
    )

# ── ARIA project tag written into Overleaf project name prefix ────────────────
_ARIA_TAG = "[ARIA]"
_OVERLEAF_HOST = "www.overleaf.com"


# ══════════════════════════════════════════════════════════════════════════════
# IEEEtran LaTeX Template Builder
# ══════════════════════════════════════════════════════════════════════════════

def build_ieeeetran_latex(
    title: str,
    authors: str,
    abstract: str,
    body_sections: Dict[str, str],
    references: List[Dict],
    journal: str = "IEEE Transactions",
) -> tuple[str, str]:
    """
    Build a complete IEEEtran-formatted .tex file and .bib bibliography.

    Args:
        title: Paper title.
        authors: Author line string.
        abstract: Abstract paragraph text.
        body_sections: OrderedDict of {section_title: section_body_latex}.
        references: List of {key, author, title, journal, year, volume, pages} dicts.
        journal: Target journal name (used in a comment only).

    Returns:
        Tuple of (main_tex_content, bibliography_bib_content).
    """
    now = datetime.now().strftime("%B %Y")

    # ── Build body ─────────────────────────────────────────────────────────
    body_parts = []
    roman = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]
    for i, (sec_title, sec_body) in enumerate(body_sections.items()):
        r = roman[i] if i < len(roman) else str(i + 1)
        body_parts.append(f"\\section{{{sec_title}}}")
        body_parts.append(sec_body.strip())

    body_latex = "\n\n".join(body_parts)

    # ── Build bibliography ──────────────────────────────────────────────────
    bib_entries = []
    for ref in references:
        key = ref.get("key", f"ref{ref.get('n', 1)}")
        author = ref.get("author", "Author, A.")
        title = ref.get("title", "Untitled")
        journal_name = ref.get("journal", "IEEE Transactions")
        year = ref.get("year", str(datetime.now().year))
        volume = ref.get("volume", "1")
        pages = ref.get("pages", "1--10")
        bib_entries.append(
            f"@article{{{key},\n"
            f"  author  = {{{author}}},\n"
            f"  title   = {{{{{title}}}}},\n"
            f"  journal = {{{journal_name}}},\n"
            f"  year    = {{{year}}},\n"
            f"  volume  = {{{volume}}},\n"
            f"  pages   = {{{pages}}}\n"
            f"}}"
        )

    bib_content = "\n\n".join(bib_entries) if bib_entries else (
        "@article{placeholder,\n"
        "  author  = {Author, A.},\n"
        "  title   = {{Placeholder Reference}},\n"
        "  journal = {IEEE Transactions},\n"
        "  year    = {2024}\n"
        "}"
    )

    # ── Build cite commands for the references section ──────────────────────
    cite_keys = [ref.get("key", f"ref{ref.get('n', i+1)}") for i, ref in enumerate(references)]

    tex_content = r"""\documentclass[journal]{IEEEtran}

%% ── Core Packages ──────────────────────────────────────────────
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{algorithmic}
\usepackage{array}
\usepackage{textcomp}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{url}
\usepackage{cite}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}

%% ── Metadata ────────────────────────────────────────────────────
%% Target Journal: """ + journal + r"""
%% Generated by ARIA v2.0 — """ + now + r"""

\begin{document}

\title{""" + _latex_escape(title) + r"""}

\author{""" + _latex_escape(authors) + r"""\thanks{Generated by ARIA v2.0 — AI Research \& Intelligence Assistant. Local LLM synthesis from researcher-provided literature.}}

\maketitle

\begin{abstract}
""" + abstract.strip() + r"""
\end{abstract}

\begin{IEEEkeywords}
machine learning, natural language processing, retrieval-augmented generation, IEEE research automation, local LLM
\end{IEEEkeywords}

""" + body_latex + r"""

\bibliographystyle{IEEEtran}
\bibliography{references}

\end{document}
"""

    return tex_content, bib_content


def _latex_escape(text: str) -> str:
    """Escape special LaTeX characters in plain text strings."""
    replacements = [
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
        ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    for char, escaped in replacements:
        text = text.replace(char, escaped)
    return text


# ══════════════════════════════════════════════════════════════════════════════
# OVERLEAF SERVICE CLASS
# ══════════════════════════════════════════════════════════════════════════════

class OverleafService:
    """
    Manages pushing ARIA-generated research papers to Overleaf.

    Lifecycle:
      1. `ensure_connected()` — reads browser cookies, asserts connectivity
      2. `push_paper_to_overleaf(...)` — creates project, uploads .tex + .bib
      3. `list_aria_projects()` — lists all projects with [ARIA] prefix
      4. `delete_project(project_id)` — removes a project from Overleaf
    """

    def __init__(self, browser: str = "chrome"):
        """
        Args:
            browser: 'chrome' or 'firefox'. Used by browser_cookie3 to find cookies.
        """
        self._browser = browser.lower()
        self._api: Optional[Any] = None  # pyoverleaf.Api instance
        self._connected = False
        self._last_login_attempt: Optional[float] = None
        self._login_cooldown = 60.0  # seconds between re-login attempts

    # ── Connection ────────────────────────────────────────────────────────────

    def ensure_connected(self) -> bool:
        """
        Ensure the pyoverleaf API session is active.
        Reads cookies from the user's browser — no password needed.

        Returns:
            True if connected successfully, False if pyoverleaf is not installed
            or cookies cannot be found.
        """
        if not _PYOVERLEAF_AVAILABLE:
            logger.error("[Overleaf] pyoverleaf is not installed.")
            return False

        if self._connected and self._api is not None:
            return True

        now = time.time()
        if (self._last_login_attempt is not None and
                now - self._last_login_attempt < self._login_cooldown):
            logger.debug("[Overleaf] Login cooldown active.")
            return False

        self._last_login_attempt = now

        try:
            self._api = OverleafApi()
            self._api.login_from_browser(browser=self._browser)
            # Quick connectivity test
            projects = self._api.get_projects()
            self._connected = True
            logger.info(
                f"[Overleaf] Connected via {self._browser} cookies. "
                f"Found {len(projects)} existing projects."
            )
            return True
        except Exception as exc:
            self._connected = False
            self._api = None
            logger.error(f"[Overleaf] Connection failed: {exc}")
            return False

    def get_connection_status(self) -> Dict[str, Any]:
        """Return current connection status dict for the API/dashboard."""
        return {
            "available": _PYOVERLEAF_AVAILABLE,
            "connected": self._connected,
            "browser": self._browser,
            "message": (
                "Connected" if self._connected
                else ("pyoverleaf not installed" if not _PYOVERLEAF_AVAILABLE
                      else "Not connected — ensure you are logged into Overleaf in your browser")
            ),
        }

    # ── Core: Push Paper to Overleaf ─────────────────────────────────────────

    async def push_paper_to_overleaf(
        self,
        title: str,
        tex_content: str,
        bib_content: str,
        journal: str = "IEEE Transactions",
    ) -> Dict[str, Any]:
        """
        Create a new Overleaf project and upload the generated LaTeX paper.

        Steps:
          1. Create project via Overleaf REST API (POST /project)
          2. Get root folder ID from project file tree
          3. Upload main.tex (create as Overleaf 'doc')
          4. Upload references.bib as a file
          5. Return project URL

        Args:
            title: Paper title — also used as the Overleaf project name.
            tex_content: Full .tex file content string.
            bib_content: BibTeX .bib file content string.
            journal: Target journal (informational only).

        Returns:
            Dict with: project_id, project_url, project_name, status
        """
        if not self.ensure_connected():
            raise RuntimeError(
                "Cannot connect to Overleaf. "
                "Ensure you are logged into Overleaf in Chrome or Firefox and "
                "that pyoverleaf is installed (`pip install pyoverleaf`)."
            )

        project_name = f"{_ARIA_TAG} {title[:70]}"
        logger.info(f"[Overleaf] Creating project: '{project_name}'")

        # ── Step 1: Create new Overleaf project ───────────────────────────
        try:
            project_id = self._create_project(project_name)
            logger.info(f"[Overleaf] Project created: {project_id}")
        except Exception as exc:
            raise RuntimeError(f"Failed to create Overleaf project: {exc}") from exc

        # ── Step 2: Get root folder ID ────────────────────────────────────
        try:
            root_folder = self._api.project_get_files(project_id)
            root_folder_id = root_folder.id
            logger.info(f"[Overleaf] Root folder ID: {root_folder_id}")
        except Exception as exc:
            raise RuntimeError(f"Failed to get project folder structure: {exc}") from exc

        # ── Step 3: Find and replace or create main.tex ───────────────────
        try:
            self._upload_doc(project_id, root_folder, root_folder_id, "main.tex", tex_content)
            logger.info("[Overleaf] Uploaded main.tex")
        except Exception as exc:
            logger.warning(f"[Overleaf] main.tex upload warning: {exc}")

        # ── Step 4: Upload references.bib ─────────────────────────────────
        try:
            bib_bytes = bib_content.encode("utf-8")
            self._api.project_upload_file(
                project_id,
                root_folder_id,
                "references.bib",
                io.BytesIO(bib_bytes),
            )
            logger.info("[Overleaf] Uploaded references.bib")
        except Exception as exc:
            logger.warning(f"[Overleaf] references.bib upload warning: {exc}")

        project_url = f"https://{_OVERLEAF_HOST}/project/{project_id}"
        logger.info(f"[Overleaf] Paper ready at: {project_url}")

        return {
            "status": "success",
            "project_id": project_id,
            "project_name": project_name,
            "project_url": project_url,
            "journal": journal,
            "created_at": datetime.now().isoformat(),
        }

    # ── List & Delete Projects ────────────────────────────────────────────────

    def list_aria_projects(self) -> List[Dict[str, Any]]:
        """
        List all Overleaf projects created by ARIA (prefixed with [ARIA]).

        Returns:
            List of project info dicts.
        """
        if not self.ensure_connected():
            return []

        try:
            all_projects = self._api.get_projects()
            aria_projects = [
                {
                    "project_id": p.id,
                    "project_name": p.name,
                    "project_url": f"https://{_OVERLEAF_HOST}/project/{p.id}",
                    "last_updated": p.last_updated,
                    "access_level": p.access_level,
                }
                for p in all_projects
                if p.name.startswith(_ARIA_TAG) and not p.archived and not p.trashed
            ]
            logger.info(f"[Overleaf] Found {len(aria_projects)} ARIA projects.")
            return aria_projects
        except Exception as exc:
            logger.error(f"[Overleaf] Failed to list projects: {exc}")
            return []

    def list_all_projects(self) -> List[Dict[str, Any]]:
        """List ALL Overleaf projects (not just ARIA ones)."""
        if not self.ensure_connected():
            return []
        try:
            all_projects = self._api.get_projects()
            return [
                {
                    "project_id": p.id,
                    "project_name": p.name,
                    "project_url": f"https://{_OVERLEAF_HOST}/project/{p.id}",
                    "last_updated": p.last_updated,
                    "is_aria": p.name.startswith(_ARIA_TAG),
                }
                for p in all_projects
                if not p.archived and not p.trashed
            ]
        except Exception as exc:
            logger.error(f"[Overleaf] list_all_projects failed: {exc}")
            return []

    def delete_project(self, project_id: str) -> Dict[str, str]:
        """
        Delete an Overleaf project by ID.
        Only projects prefixed with [ARIA] are allowed to be deleted for safety.

        Returns:
            Status dict.
        """
        if not self.ensure_connected():
            raise RuntimeError("Not connected to Overleaf.")

        try:
            # Safety check — only delete ARIA-tagged projects
            projects = self._api.get_projects()
            target = next((p for p in projects if p.id == project_id), None)
            if target is None:
                raise ValueError(f"Project {project_id} not found.")
            if not target.name.startswith(_ARIA_TAG):
                raise PermissionError(
                    f"ARIA will only delete projects it created (prefixed with '{_ARIA_TAG}'). "
                    f"Project '{target.name}' was not created by ARIA."
                )

            # Overleaf API: trash then delete
            session = self._api._get_session()
            csrf = self._api._get_csrf_token()
            base = f"https://{_OVERLEAF_HOST}"

            # Trash first
            r = session.post(
                f"{base}/project/{project_id}/trash",
                json={"_csrf": csrf},
                timeout=16,
            )
            r.raise_for_status()

            # Then permanently delete
            r = session.delete(
                f"{base}/project/{project_id}",
                json={"_csrf": csrf},
                timeout=16,
            )
            r.raise_for_status()

            logger.info(f"[Overleaf] Deleted project {project_id} ('{target.name}')")
            return {"status": "deleted", "project_id": project_id, "project_name": target.name}

        except (ValueError, PermissionError) as exc:
            raise
        except Exception as exc:
            logger.error(f"[Overleaf] Delete failed for {project_id}: {exc}")
            raise RuntimeError(f"Delete failed: {exc}") from exc

    def download_project(self, project_id: str, output_path: str) -> str:
        """Download an Overleaf project as a .zip file."""
        if not self.ensure_connected():
            raise RuntimeError("Not connected to Overleaf.")
        self._api.download_project(project_id, output_path)
        logger.info(f"[Overleaf] Downloaded project {project_id} → {output_path}")
        return output_path

    # ── Private Helpers ───────────────────────────────────────────────────────

    def _create_project(self, project_name: str) -> str:
        """
        Create a new blank Overleaf project via the internal REST API.
        pyoverleaf doesn't expose this yet, so we call it directly
        using the authenticated session.

        Returns:
            New project ID string.
        """
        session = self._api._get_session()
        csrf = self._api._get_csrf_token()

        payload = {
            "projectName": project_name,
            "_csrf": csrf,
        }

        r = session.post(
            f"https://{_OVERLEAF_HOST}/project/new",
            data=payload,
            timeout=20,
            allow_redirects=True,
        )
        r.raise_for_status()

        # Extract project ID from redirect URL or response JSON
        # Overleaf redirects to /project/{id} after creation
        final_url = r.url
        match = re.search(r"/project/([a-f0-9]{24})", final_url)
        if match:
            return match.group(1)

        # Fallback: try JSON body
        try:
            data = r.json()
            pid = data.get("project_id") or data.get("id")
            if pid:
                return pid
        except Exception:
            pass

        # Fallback: parse HTML for project ID
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(r.content, "html.parser")
        meta = soup.find("meta", {"name": "ol-project_id"})
        if meta and meta.get("content"):
            return meta["content"]

        raise RuntimeError(
            f"Could not extract project ID from Overleaf response. "
            f"Final URL: {final_url}\nStatus: {r.status_code}"
        )

    def _upload_doc(
        self,
        project_id: str,
        root_folder: Any,
        folder_id: str,
        doc_name: str,
        content: str,
    ):
        """
        Create or replace a document (e.g., main.tex) inside a project.
        First tries to find an existing doc with that name and delete it,
        then creates a fresh one.
        """
        lines = content.splitlines()

        # Delete existing doc with same name if present (can't update in-place via pyoverleaf)
        try:
            for child in root_folder.children:
                if child.name == doc_name and child.type == "doc":
                    self._api.project_delete_entity(project_id, "doc", child.id)
                    logger.debug(f"[Overleaf] Removed old {doc_name}")
                    break
        except Exception:
            pass  # ignore — maybe it didn't exist

        self._api.project_create_doc(project_id, folder_id, doc_name, lines)
